### ISSUE TITLE
 Use of deprecated UIWebView

### ISSUE THREAD

**Issue by diegogurpegui** [zoho/SalesIQ-Mobilisten-iOS#10]
Could it be that this SDK is not updated to the guidelines of Apple regarding the use of UIWebView?
Apple is not accepting apps that use UIWebView any more:
> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

We're using the [React Native SDK](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative), which has outdated binaries. We tried to replace the binaries reference with the ones in this project, which seems more active. However, we are still getting the same error from Apple.
Related issue on the React Native SDK: https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/issues/2

Is anyone else having this problem?
Could you confirm that this is working please?

**Comment by Rishabh-Raghunath** [comment]
We have already updated Mobilisten to use WKWebView from pod version 1.1.2.
Updating the version of Mobilisten used in the project should resolve this issue.
