### ISSUE TITLE
On 17 Sept 2020 Xcode 12 will be released

### ISSUE THREAD

**Issue by appstab-Dani** [zoho/SalesIQ-Mobilisten-iOS#12]
Hi!

Tomorrow (17 Sept 2020) the new Xcode will be released, would you mind to update Mobilisten with the new swift compiler?

If you guys are looking before it, Xcode GM is available to download as right now

Thanks!

**Comment by Rishabh-Raghunath** [comment]
Hi @appstab-Dani, 
You should be able to use the XCFramework version of the Mobilisten pod irrespective of the swift compiler version used starting from **Xcode 11.4 and above**.
The latest version of Mobilisten that is built as an XCFramework would be v[3.4.2](https://github.com/zoho/SalesIQ-Mobilisten-iOS/releases/tag/v3.4.2).
Please try this version out on Xcode 12 and let us know.

**Comment by appstab-Dani** [comment]
You are right! it worked 👍 

We just had to refactor some of the methods because we had an older version of the library and we are back in business :) 

Thanks guys!
