### ISSUE TITLE
live chat not sending to panel 

### ISSUE THREAD

**Issue by stnwj** [zoho/SalesIQ-Mobilisten-iOS#14]
this my code registervisitor
` @IBAction func onClickBtnChatSpradz(_ sender: Any) {
        print(idMember ?? "")
        ZohoSalesIQ.registerVisitor(idMember)
        ZohoSalesIQ.Visitor.setName(namaMember)
        ZohoSalesIQ.Visitor.setEmail(email)
        ZohoSalesIQ.Visitor.setQuestion("Saya butuh bantuan terkait hal...")
        ZohoSalesIQ.Chat.show()
    }`

What my mistake?
when i tried to chat with zoho. my chat not sending to panel dashboard
Running on simulator. 
<img width="1280" alt="Screen Shot 2020-12-18 at 16 28 10" src="https://user-images.githubusercontent.com/43704613/102598076-0f025e00-414e-11eb-9f2d-e3aef4c021e8.png">

when i first click always error  like this
<img width="1280" alt="Screen Shot 2020-12-18 at 16 40 12" src="https://user-images.githubusercontent.com/43704613/102599281-d82d4780-414f-11eb-8b1c-c9137b2145ff.png">

**Comment by Rishabh-Raghunath** [comment]
@stnwj The support chat requests were created successfully from your device.
However, it looks like all operators were offline at the time causing the requests to be missed after a certain idle time.
​You would need to hop on to the SalesIQ dashboard and mark your status as ***Available*** *(toggle at the top right corner)* to start receiving chat requests from your users.

You could refer to [this](https://www.zoho.com/salesiq/help/getting-started-basics-of-salesiq.html) article we have to get up to speed using SalesIQ 🙂 
If you have further queries, do feel free to drop us a mail at **support@zohosalesiq.com**
We are closing this issue now.
