### ISSUE TITLE
Issue: Cannot create new conversations with specific VisitorID

### ISSUE THREAD

**Issue by lvandyk** [zoho/SalesIQ-Mobilisten-iOS#16]
**Describe the bug**
Cannot create a new conversation using a specific VisitorID anymore: ```[ZohoSalesIQ registerVisitor:@"2500"];```

**To Reproduce**
1. Open SDK 
2. Tap on blue 'New Conversation' icon
3. User details form appears, filling in all fields and tapping 'Submit' causes the 'Submit' button to simply shake and vibrate. The conversation does not get created.

**Expected behavior**
The conversation should be created.

**Screenshots**
Here is a video showing the issue: https://imgur.com/a/JnF7fG8

**Smartphone (please complete the following information):**
- Do you usually run the project on the simulator or a physical device? Both
 - Device: iPhone 8
 - OS: iOS 14.4
 - Xcode Version: 12.4
 - Mobilisten Version: 3.6.4

**Additional context**
It only happens for a specific visitor ID: ```[ZohoSalesIQ registerVisitor:@"2500"]```. It used to work.

**Comment by Rishabh-Raghunath** [comment]
@lvandyk Thanks for reaching out.
Just so I understand the issue better, you say the behavior happens only if the visitor ID is set to "2500" ?

**Comment by lvandyk** [comment]
@Rishabh-Raghunath Yes. I just did this: ```[ZohoSalesIQ registerVisitor:@"ANYOTHERVALUE"];``` and it worked perfectly.

**Comment by Rishabh-Raghunath** [comment]
@lvandyk We have identified the issue and have taken steps to addressed this on our end.
There would be no changes required in the app (or) the SDK and it should work right away once the app is opened.

We request you to confirm if this issue is solved.

**Comment by lvandyk** [comment]
@Rishabh-Raghunath We tested and its now working! Thank you for the quick turnaround!
