### ISSUE TITLE
Issue: No visible @interface for 'LCSharedHandler' declares the selector 'show:'

### ISSUE THREAD

**Issue by bala-kredx** [zoho/SalesIQ-Mobilisten-iOS#17]
**Describe the bug**
While trying to generate a build in iOS, getting the error: No visible @interface for 'LCSharedHandler' declares the selector 'show:'

**To Reproduce**
1. In my existing react native app, added pod
`pod 'Mobilisten','3.6.4'`
2. Delete `podfile.lock` and `Pods` folder
3. `pod repo update && pod install`
4. Clean Project and build in Xcode 
5. See error: `No visible @interface for 'LCSharedHandler' declares the selector 'show:'`

**Expected behavior**
Successful build generation for iOS 

**Screenshots**
<img width="780" alt="Screenshot 2021-03-30 at 11 24 47 AM" src="https://user-images.githubusercontent.com/76196876/112940274-8af74380-914a-11eb-8487-0e99ecd1d93c.png">

**Smartphone (please complete the following information):**
- Do you usually run the project on the simulator or a physical device? Simulator
 - Device:  iPhone 11
 - OS: iOS 14.4
 - Xcode Version: 12.4
 - Mobilisten Version: 3.6.4
 - Machine Configuration: MacOS 11.2.3 | MacBook Pro 2017 | Dual-Core Intel Core i5
 
 **Additional Information**
 - Tried both manual and automatic installation methods at [Zoho's official site](https://www.zoho.com/salesiq/help/developer-section/ios-mobile-sdk-installation.html)

**Comment by Rishabh-Raghunath** [comment]
@bala-kredx The **`ZohoSalesIQ.Chat.show`** API has been used incorrectly here.
You can find the documentation for this API [here](https://www.zoho.com/salesiq/help/developer-section/ios-sdk-chat-show-v3.html).

Here is the example code snippet that should work:
```swift
RCT_EXPORT_METHOD(openChat){
    dispatch_async(dispatch_get_main_queue(), ^{
        [[ZohoSalesIQ Chat] showWithReferenceID:nil new:NO];
    });
}
```

**Comment by Rishabh-Raghunath** [comment]
We hope that the API reference provided answers your question.
This issue is being closed. Feel free to add more comments here in case you have further queries.
