### ISSUE TITLE
Cannot use with XCode 11 last update

### ISSUE THREAD

**Issue by batuhanc** [zoho/SalesIQ-Mobilisten-iOS#2]
There is already an issue that is opened like 10 days ago but with no replies, opening a new issue to get the devs attention. SDK is currently unusable after latest XCode 11 update. The error is;

`Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler`

**Comment by Rishabh-Raghunath** [comment]
Hey batuhanc,
Please check the below repository for the updated Mobilisten SDK compiled using Swift 5.1 and initial iOS 13 support.
**MobilistenBeta Repo**: https://github.com/zoho/Mobilisten-iOS-Beta

**Comment by batuhanc** [comment]
Sorry for the late response, thank you it works
