### ISSUE TITLE
Right now faced one more issue, the sdk is initialized but I am getting the following error, and no window is visible;

### ISSUE THREAD

**Issue by ammarmarn** [zoho/SalesIQ-Mobilisten-iOS#21]
Right now faced one more issue, the sdk is initialized but I am getting the following error, and no window is visible;

`"Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service"`

_Originally posted by @ammarmarn in https://github.com/zoho/SalesIQ-Mobilisten-iOS/issues/20#issuecomment-922989881_

**Comment by Rishabh-Raghunath** [comment]
Closing this issue since the message is not related to the reported behavior.
The discussion shall take place in the original report.

Thanks
