### ISSUE TITLE
Issue: Unable to Build Project using the CocoaPod dependency in Xcode 13.1

### ISSUE THREAD

**Issue by tundechaka** [zoho/SalesIQ-Mobilisten-iOS#22]
**Describe the bug**

I am unable to build an iOS project that uses the Mobilisten 4.2.4 release with Xcode 13.1

**To Reproduce**
1. Add Mobilisten to Podfile
2. Run pod install
3. Clean build folder
4. Build Xcode project
3. See error

**Expected behavior**
Project should build correctly without errors

**Screenshots**
<img width="605" alt="Screenshot 2022-01-27 at 5 18 33 AM" src="https://user-images.githubusercontent.com/79566062/151339391-2c97e8dc-e789-440f-83c7-ec2d24def4a6.png">
<img width="1410" alt="Screenshot 2022-01-27 at 5 18 02 AM" src="https://user-images.githubusercontent.com/79566062/151339395-1080c919-83c2-4802-a367-5390d50823fe.png">
<img width="1403" alt="Screenshot 2022-01-27 at 5 17 41 AM" src="https://user-images.githubusercontent.com/79566062/151339404-0dd3f24d-a354-4861-baa8-b0ed0f62dc62.png">

**Smartphone (please complete the following information):**
- Do you usually run the project on the simulator or a physical device?
 - Device: iPhone 8
 - OS: iOS 15.2.1
 - Xcode Version: [e.g. 13.1]
 - Mobilisten Version: [e.g. 4.2.4]

**Additional context**
Please note that the failure happens before the app is installed on a device, it happens whenever I attempt to build the project

Here's the error shown in Xcode:
Category 'SRWebSocket' on interface 'NSRunLoop' has different definitions in different modules; first difference is definition in module 'Mobilisten.LDSRWebSocket' found return type is 'NSRunLoop *'

**Comment by Rishabh-Raghunath** [comment]
Hi @tundechaka, thank you for bringing this issue to our notice.
We are working towards a solution for this issue and will be keeping you posted here regarding further updates.

**Comment by tundechaka** [comment]
Awesome, thanks @Rishabh-Raghunath!
Looking forward to a successful fix :)

**Comment by tundechaka** [comment]
Hi @Rishabh-Raghunath , is there any update on this yet?

**Comment by Rishabh-Raghunath** [comment]
Hello @tundechaka, this issue should now be addressed in release [4.2.5](https://github.com/zoho/SalesIQ-Mobilisten-iOS/releases/tag/v4.2.5) of Mobilisten.
We request you to update Mobilisten to the above version and give it a go.

**Comment by tundechaka** [comment]
Hi @Rishabh-Raghunath 
The issue is confirmed fixed!

Thank you for your responsiveness, will reach out if anything else comes up 👍
