### ISSUE TITLE
Don't know that error

### ISSUE THREAD

**Issue by peterkuch** [zoho/SalesIQ-Mobilisten-iOS#24]
![Screen Shot 2022-05-11 at 2 39 09 PM](https://user-images.githubusercontent.com/14107698/167795107-c72712d9-9272-4c68-81f1-d0b31257e927.png)
Latest for ios

Crashed: com.messageentity.serialQueue
0  Mobilisten                     0x1b272c block_destroy_helper + 11400
1  Mobilisten                     0x1b2a10 block_destroy_helper + 12140
2  libswiftDispatch.dylib         0x2598 partial apply for thunk for @callee_guaranteed () -> (@out A, @error @owned Error) + 28
3  libswiftDispatch.dylib         0x9af8 thunk for @callee_guaranteed () -> (@out A, @error @owned Error)partial apply + 16
4  libswiftDispatch.dylib         0x3958 closure #1 in closure #1 in OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 188
5  libswiftDispatch.dylib         0x3a6c partial apply for thunk for @callee_guaranteed () -> () + 28
6  libswiftDispatch.dylib         0x3384 thunk for @escaping @callee_guaranteed () -> () + 28
7  libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
8  libdispatch.dylib              0x12c90 _dispatch_lane_barrier_sync_invoke_and_complete + 56
9  libswiftDispatch.dylib         0x2cac implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 180
10 libswiftDispatch.dylib         0x1d0c partial apply for implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 56
11 libswiftDispatch.dylib         0x29ec OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 396
12 libswiftDispatch.dylib         0x1dbc OS_dispatch_queue.sync<A>(execute:) + 168
13 Mobilisten                     0x1b017c block_destroy_helper + 1752
14 Mobilisten                     0x2e3af4 block_destroy_helper + 24628
15 Mobilisten                     0x2e3728 block_destroy_helper + 23656
16 Mobilisten                     0x2e360c block_destroy_helper + 23372
17 Mobilisten                     0x2447b0 block_destroy_helper.42 + 9828
18 Mobilisten                     0x8e288 block_destroy_helper.86 + 1304
19 libdispatch.dylib              0x1e68 _dispatch_call_block_and_release + 32
20 libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
21 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
22 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
23 CoreFoundation                 0x522f0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
24 CoreFoundation                 0xc1f4 __CFRunLoopRun + 2532
25 CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
26 GraphicsServices               0x1374 GSEventRunModal + 164
27 UIKitCore                      0x513e88 -[UIApplication _run] + 1100
28 UIKitCore                      0x2955ec UIApplicationMain + 364
29 Z1                             0x20cf8 main + 18 (AppDelegate.swift:18)
30 ???                            0x1059fdce4 (Missing)

**Comment by Rishabh-Raghunath** [comment]
Hello @peterkuch, thanks for the report.
It would be helpful if you could attach the symbolicated crash report to help us gain more insight.

Could you also help us with the frequency at which this is being observed?

**Comment by peterkuch** [comment]
> Hello @peterkuch, thanks for the report. It would be helpful if you could attach the symbolicated crash report to help us gain more insight.
> 
> Could you also help us with the frequency at which this is being observed?

I don't understand what do you want?

**Comment by Rishabh-Raghunath** [comment]
The crash report you have shared is unsymbolicated. We would like you to share the symbolicated crash report in order for us to gain more insight. You can find more information about symbolicating crash reports [here](https://developer.apple.com/documentation/xcode/adding-identifiable-symbol-names-to-a-crash-report).

The dSYM files for the Mobilisten can be found within the xcframework for symbolication if required.

**Comment by peterkuch** [comment]
> The crash report you have shared is unsymbolicated. We would like you to share the symbolicated crash report in order for us to gain more insight. You can find more information about symbolicating crash reports [here](https://developer.apple.com/documentation/xcode/adding-identifiable-symbol-names-to-a-crash-report).
> 
> The dSYM files for the Mobilisten can be found within the xcframework for symbolication if required.
[Bhkwd9tSfA_7izDCUWiPlB.xccrashpoint.zip](https://github.com/zoho/SalesIQ-Mobilisten-iOS/files/8675133/Bhkwd9tSfA_7izDCUWiPlB.xccrashpoint.zip)
Our log please can check it.

**Comment by Rishabh-Raghunath** [comment]
Thanks for the report. We'll investigate this further and keep posted here.

**Comment by Rishabh-Raghunath** [comment]
Hi @peterkuch, we have resolved this issue with Release [4.2.8](https://github.com/zoho/SalesIQ-Mobilisten-iOS/releases/tag/v4.2.8). We request you to upgrade to this version.
Thanks.
