### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by HadyHammad22** [zoho/SalesIQ-Mobilisten-iOS#26]
When click on close log icon the app crash
<img width="1440" alt="Screen Shot 2022-08-25 at 1 50 27 PM" src="https://user-images.githubusercontent.com/53533148/186659297-e55d7345-6be9-4597-aa3a-6fc604a8f510.png">

**Comment by Venkatesh-iOS** [comment]
Hi HadyHammad22,

Thanks for reporting the issue. We're checking the issue and will keep you posted regarding the updates. 

Regards,
Venkatesh
Zoho SalesIQ

**Comment by Venkatesh-iOS** [comment]
Hello @HadyHammad22 

Thank you for bringing the app crash issue to our attention. We apologize for any inconvenience this may have caused. 
The reported issue has been successfully resolved in the latest update, version [6.0.0](https://github.com/zoho/SalesIQ-Mobilisten-iOS/releases/tag/v6.0.0). 
We recommend updating to this version. 

If you have any further questions or concerns,  please feel free to contact us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com)

Best regards,
Venkatesh,
Zoho SalesIQ
