### ISSUE TITLE
Issue: Not supported properly for swiftui based projects

### ISSUE THREAD

**Issue by vishal-jadav** [zoho/SalesIQ-Mobilisten-iOS#28]
Sometimes zoho launcher not showing on appear view for swiftui based project - ZohoSalesIQ.showLauncher(true)

**Comment by Venkatesh-iOS** [comment]
Hello @vishal-jadav 

Thank you for bringing the issue to our attention. We have thoroughly checked the mentioned problem with SwiftUI, and it is working correctly on our end.

To help us investigate further and resolve your issue, please help us with the exact scenario or steps where you have faced this problem. Any additional information or context you can share will be valuable for our debugging process.

Please feel free to contact our support team at  [support@zohosalesiq.com](mailto:support@zohosalesiq.com).


Best regards,
Venkatesh
Zoho SalesIQ

**Comment by vishal-jadav** [comment]
Hello @Venkatesh-iOS  ,

This issue is not occurring every time. basically we have customised Zoho launcher theme using ZohoSalesIQ.Theme.setTheme(theme: customTheme) and then showing launcher using ZohoSalesIQ.showLauncher(true) in .onAppear event but sometimes launcher not showing. This issue is not occurring every time but there is some issue in launcher appear for swiftui based project.

**Comment by Venkatesh-iOS** [comment]
Hi @vishal-jadav 

Greetings from Zoho SalesIQ. We looked into the issue and tried reproducing it for a better understanding. Unfortunately, we couldn't reproduce it. So, please write us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to help you.

Best regards,
Venkatesh,
Zoho SalesIQ
