### ISSUE TITLE
Issue: Mobile SDK Crash

### ISSUE THREAD

**Issue by burakcolakappcent** [zoho/SalesIQ-Mobilisten-iOS#30]
**Describe the bug**
This bug happens on client no matter he is on chat screen or not, it looks like there is some unguarded variable problem.

**To Reproduce**
1. Go to app
2. Navigation one or two screen
3. Wait some time
4. After some time there is a crash

**Expected behavior**
There should not be a crash

**Screenshots**
![Screenshot 2024-03-21 at 15 49 03](https://github.com/zoho/SalesIQ-Mobilisten-iOS/assets/53617114/58d0e6c3-d155-4f45-87fd-39497e858a5d)

**Smartphone (please complete the following information):**
- Do you usually run the project on the simulator or a physical device? Physical device
 - Device: iPhone 13 Pro Max
 - OS: iOS 17.4
 - Xcode Version: 15.3
 - Mobilisten Version: 8.0.2

**Comment by venkatesh-ramesh-12517** [comment]
Hi @burakcolakappcent 

We apologize for any inconvenience this may have caused. We have fixed the issue and are planning to roll out the update soon. We will keep you posted on the same. 

Thank you for your patience and understanding.

Regards,
Venkatesh R,
Zoho SalesIQ.

**Comment by burakcolakappcent** [comment]
Is there any update, thanks @venkatesh-ramesh-12517

**Comment by venkatesh-ramesh-12517** [comment]
Hi @burakcolakappcent 

Thank you for contacting us. We've fixed this issue in our latest update. Please update the to Mobilisten SDK version [8.1.2](https://github.com/zoho/SalesIQ-Mobilisten-iOS/releases/tag/v8.1.2).

Please feel free to write back to us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com) for further assistance. 

Regards,
Venkatesh R,
Zoho SalesIQ.

**Comment by burakcolakappcent** [comment]
Thanks, we updated already to 8.1.1, now upgraded to 8.1.2 as well, will check and get back to you if there is any problem or crash, regards.

Burak

**Comment by burakcolakappcent** [comment]
Hi @venkatesh-ramesh-12517 I saw that you published major version 9.
Should we need to update our SDK to that version, or is it okay to be stay in 8.1.3.
Or this major version has also this patch ?

Regards,
Burak

**Comment by venkatesh-ramesh-12517** [comment]
Hi @burakcolakappcent 
 
Please use the updated SDK version [9.0.3](https://github.com/zoho/SalesIQ-Mobilisten-iOS/releases/tag/v9.0.3). This major version includes essential updates to the privacy manifest file, ensuring compliance with Apple's latest privacy regulations.
 
Best regards,
Venkatesh
Zoho SalesIQ

**Comment by burakcolakappcent** [comment]
Hi @venkatesh-ramesh-12517 
We updated SDK to 9.0.3 and its working fine.
