### ISSUE TITLE
Feature Request: Localization exemple for registerLocalizationFile()

### ISSUE THREAD

**Issue by theomendes** [zoho/SalesIQ-Mobilisten-iOS#31]
Hello, how are you?

I'm not sure if this is the most suitable place to clarify this doubt, but I couldn't find another one.

I need to customize the strings used by SalesIQ. I saw in the iOS documentation the function registerLocalizationFile(), however, I couldn't find anywhere else a list with all the strings used. I found only in the Android documentation, but from what I saw, they are not the same.

Would you know where I can find this information?

**Comment by venkatesh-ramesh-12517** [comment]
Hi @theomendes 

We apologize for the inconvenience caused. We are actively working on compiling a list of string keys for customization. If you need any specific keys for customization, please contact our support team at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to assist you.

Regards,
Venkatesh R,
Zoho SalesIQ.

**Comment by venkatesh-ramesh-12517** [comment]
Hello @theomendes 

Thank you for reaching out. We appreciate your patience as we've worked on compiling a list of string keys for customization in SalesIQ.
You can find the list of string keys for customization in the SalesIQ iOS SDK documentation under the [.registerLocalizationFile()](https://www.zoho.com/salesiq/help/developer-section/ios-sdk-register-localization-file.html) function.

If you have any further questions or need assistance with specific keys for customization, please don't hesitate to contact our dedicated support team at [support@zohosalesiq.com](mailto:support@zohosalesiq.com).


Regards,
Venkatesh R,
Zoho SalesIQ.
