### ISSUE TITLE
Issue: Getting crash while open the chat with chat.show()

### ISSUE THREAD

**Issue by DhavalUmraliya** [zoho/SalesIQ-Mobilisten-iOS#34]
**Describe the bug**
Im trying to open chat window from single ton class. sometime its working some time its crash.

**To Reproduce**
I have one common function to open chat window. when i open chat window from profile its working and then open that window from another screen then its crashed

**Expected behavior**
it should not crashed, if there is an error then should be print logs.

**Screenshots**
Added Screen shot

**Smartphone (please complete the following information):**
-  iphon 12 pro max

HERE IS THE CODE

class ChatbotManager:NSObject, ZohoSalesIQDelegate, ZohoSalesIQChatDelegate, ZohoSalesIQFAQDelegate {

    static let shared = ChatbotManager()

    func openChatWindow(){
        let customTheme = ZohoSalesIQ.Theme.baseTheme
        customTheme.Navigation.backgroundColor = UIColor.F03457
        customTheme.Navigation.titleColor = UIColor.FCFCFD
        customTheme.Navigation.tintColor  = UIColor.FCFCFD
        customTheme.themeColor =  UIColor.F03457
        ZohoSalesIQ.Chat.setLanguage(.english)
        ZohoSalesIQ.Chat.setTitle("Help Chat")
        ZohoSalesIQ.Theme.setTheme(theme: customTheme)
        ZohoSalesIQ.Chat.showOfflineMessage(true)

        ZohoSalesIQ.Chat.delegate = self
        DispatchQueue.main.async {
              ZohoSalesIQ.Chat.show()
          }

        ZohoSalesIQ.logProperties()
    }

}
 
<img width="1662" alt="Screenshot 2024-10-14 at 7 40 47 PM" src="https://github.com/user-attachments/assets/ddca05f0-8c68-4c23-92e2-f94f6bfe0cb1">

**Comment by venkatesh-ramesh-12517** [comment]
Hi @DhavalUmraliya 
 
Thank you for pointing this out. We are already working to resolve this issue. I will keep you posted regarding updates.
 
In the meantime, if you have any other queries, please contact our customer support team at [support@zohosalesiq.com](mailto:support@zohosalesiq.com).
 
Best regards,
Venkatesh

**Comment by venkatesh-ramesh-12517** [comment]
Hello @DhavalUmraliya 
 
We have resolved this issue in version [9.2.0](https://github.com/zoho/SalesIQ-Mobilisten-iOS/releases/tag/v9.2.0) of the SDK. Please update to the latest version and let us know if the problem persists.
 
If you encounter any further issues or need assistance, feel free to reach out at support@zohosalesiq.com
 
Best regards,
Venkatesh
