### ISSUE TITLE
unknown receiver 'ZohoSalesIQ'; did you mean 'RNZohoSalesIQ'? issue in iOS app. Can anyone know that how can be resolved it?

### ISSUE THREAD

**Issue by DimpyLadva** [zoho/SalesIQ-Mobilisten-iOS#5]
<img width="1440" alt="Screenshot 2020-01-06 at 7 01 55 PM" src="https://user-images.githubusercontent.com/10396936/71881606-9e3e7d80-3158-11ea-8e9a-65d944953668.png">

**Comment by Angu-G** [comment]
Hi @DimpyLadva can you please share your Pod file here.

**Comment by DimpyLadva** [comment]
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'vistaquoteApp' do
  # Pods for vistaquoteApp
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  pod 'RNZohoSalesIQ', :path => '../node_modules/react-native-zohosalesiq-mobilisten/ios/RNZohoSalesIQ.podspec'

  target 'vistaquoteAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'vistaquoteApp-tvOS' do
  # Pods for vistaquoteApp-tvOS

  target 'vistaquoteApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by Rishabh-Raghunath** [comment]
Hello @DimpyLadva,

Assuming the installation of the framework was successful without errors, could you confirm if you get the same issue upon trying to build the project for a non-simulator target? Please try building the project after selecting an actual device or select "Generic iOS Device" as your run target.

**Comment by DimpyLadva** [comment]
@Rishabh-Raghunath : App is working from Testflight on iPhone. Is there any permanent solution so that we can test app in simulator also?

**Comment by Thyoity** [comment]
I have the exact same problem. I need to test the app in the simulator, but every time I try to compile, it errors with these same problems shown in the screenshot

**Comment by DimpyLadva** [comment]
@Rishabh-Raghunath Can you please find the solution? As I need to use a simulator for testing, I cannot generate build every time for testing purpose.

**Comment by cernadasjuan** [comment]
Same error here with the simulator

**Comment by Rishabh-Raghunath** [comment]
This is caused due to a known issue introduced in XCode 10.2 while building universal frameworks.
We will explore a workaround solution for this and have the fix merged in the next release of Mobilisten.
Until then, If your project uses Objective-C and you get this error, please run on the device to test the support features.
You may also comment out the APIs used to run the app on the simulator alone.
This won't be an issue while running on an iOS device.
