### ISSUE TITLE
Support for Swift 5.2, Xcode Version 11.4 beta 3

### ISSUE THREAD

**Issue by appstab-Dani** [zoho/SalesIQ-Mobilisten-iOS#7]
Hi guys, 

I downloaded the beta of Xcode and now we can't compile our project because of Mobilisten

Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler: MobilistenBeta/Mobilisten.framework/Modules/Mobilisten.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

I was checking this other project:
https://github.com/zoho/Mobilisten-iOS-Beta

But it has the same problem, it is not an issue now, but it will be when Xcode will be release Swift 5.2

Thanks!

**Comment by appstab-Dani** [comment]
I can verify that it is not compiling on new released Xcode Version 11.4 (11E146)

Same compiler error

**Comment by Rishabh-Raghunath** [comment]
Hello @appstab-Dani 
We will be doing a release with the framework built using the Swift 5.2 compiler when Xcode 11.4 is released.

**Comment by appstab-Dani** [comment]
That's great to hear,

but Xcode 11.4 has already been released as 24 March, you can check the AppStore and click on version History

Thanks!

**Comment by Rishabh-Raghunath** [comment]
Mobilisten built using the Swift 5.2 compiler is now available.
Please install the updated version by adding `pod 'Mobilisten','1.1.3'` to your Podfile.

**Comment by appstab-Dani** [comment]
Excellent news!

I tried and it works perfectly, 

thanks for that!
